[build]
  functions = "functions"
  command = "pip install -r requirements.txt && streamlit run functions/streamlit/streamlit_app.py"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/streamlit"
  status = 200
